### ISSUE TITLE
Unable to compile (Ubuntu trusty)

### ISSUE THREAD

**Issue by clarktlaugh** [cosmos72/twin#1]
I am trying to compile on Ubuntu trusty and get lots of compiler errors.  Any suggestions as to how to build?

**Comment by mrhmouse** [comment]
I'm also unable to compile at changeset 74280ffd24f721e408280eb2e09f4c25e89a8722. Here's the output: https://gist.github.com/mrhmouse/1c915f91a55b18b8101b

If I run `make config` and disable the config-file parser, it compiles fine.

**Comment by mrhmouse** [comment]
Running `git bisect` implies that it broke at that commit.

**Comment by cosmos72** [comment]
Yes, rcparse.h must include rcparse_tab.h. Thanks for reporting.
Fixed in commit ead673615b46055142e1ed99447775ebe33da8c5
