### ISSUE TITLE
Compile instructions incomplete

### ISSUE THREAD

**Issue by rodneyrod** [cosmos72/twin#11]
Needed to add 'autoreconf -f -i' before './configure/ before it would compile on my Ubuntu machine, just reporting the issue

**Comment by Mirppc** [comment]
I will test this on my ubuntu system sometime in the next week.

**Comment by cosmos72** [comment]
Actually,  running "autoreconf ..." should not be needed since all files generated by autoconf/automake are already there. I am quite sure it's due to the files timestamps when you run "git clone ..." so I will add a line inside "configure" to avoid this problem

**Comment by cosmos72** [comment]
Done. Let me know if it helps.

**Comment by rodneyrod** [comment]
Fixed
