### ISSUE TITLE
Failed to run on Ubuntu 14.04 after compiling

### ISSUE THREAD

**Issue by rodneyrod** [cosmos72/twin#12]
Recieved the following error when trying to open twin:
>/usr/local/bin/twin_server: error while loading shared libraries: libTutf.so.0: cannot open shared object file: No such file or directory

After running this command I found on a forum post, it was able to open:
>sudo cp /usr/local/lib/libTutf.so.0 /usr/lib

**Comment by Mirppc** [comment]
the libtuff erro was mentioned in another post i was in.  I belive the readmen was updated with the command to do after you make install that fixes that.

**Comment by rodneyrod** [comment]
Thanks for that, I must have missed that line, I'll go ahead and close this.
