### ISSUE TITLE
Arrow keys being returned as letters in twin terminal

### ISSUE THREAD

**Issue by rodneyrod** [cosmos72/twin#13]
I'm running Finch in twin and it uses arrow keys to navigate and move some of the TUI elements.
However when I use the arrow keys in twin, it returns capital letters instead of the actual arrow key map.
e.g. Up is A, down is B, right is C and left is D.

The same occurs when using the numberpad with num lock off.

**Comment by cosmos72** [comment]
I checked, and you're right: there is a bug when running twin inside another terminal (xterm, iTerm...): special keys (arrows, home/page-up/page-down/...) are passed AS-IS to programs running inside twin terminals.

Instead they should be converted to whatever escape sequence is appropriate for TERM=linux (twin terminals emulate a linux console and thus sets TERM=linux). I will fix it.

**Comment by cosmos72** [comment]
Fixed in commit 428245b8fef24bf8c40f48efd1a450d08b47d5c8

Let me know if it works for you, or there are still issues

**Comment by rodneyrod** [comment]
Confirmed working, closing this issue.
