### ISSUE TITLE
Error during run - librarys can't open?

### ISSUE THREAD

**Issue by pentalive** [cosmos72/twin#2]
$twstart
twfindtwin: error while loading shared libraries: libTw.so.4: cannot open shared object file: No such file or directory
/usr/local/bin/twin_real: error while loading shared libraries: libTutf.so.0: cannot open shared object file: No such file or directory

./configure seemed ok
make  had many warnings but completed and said I should do make install
sudo make install completed as well -

hudson.ra@live.com

**Comment by cosmos72** [comment]
On 01/04/16 15:29, pentalive wrote:
> $twstart
> twfindtwin: error while loading shared libraries: libTwso4: cannot open
> shared object file: No such file or directory
> /usr/local/bin/twin_real: error while loading shared libraries:
> libTutfso0: cannot open shared object file: No such file or directory
>
> /configure seemed ok
> make had many warnings but completed and said I should do make install
> sudo make install completed as well -
>
> hudsonra@livecom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cosmos72/twin/issues/2>.
>
Hello pentalive,

sorry for the delay.

ensure that /etc/ld.so.conf, or one of the files it includes,
contains a line
/usr/local/lib

then run "ldconfig" as root.

This should fix the problem.

Regards,

Massimiliano Ghilardi

**Comment by pentalive** [comment]
Thanks!  That's got it.




-------------------------------------------------------------------------------------------------
Ronald Hudson.

Sent from my Linux Laptop



Date: Sun, 17 Jan 2016 14:28:38 -0800
