### ISSUE TITLE
Mouse wheel / Trackpad scrolling

### ISSUE THREAD

**Issue by dimitrik-fr** [cosmos72/twin#23]
Hello Max,

any existing or potential solution to support mouse wheel / trackpad scrolling in TWIN windows ?.. -- would be really cool ;-))

Rgds,
-Dimitri

**Comment by Mirppc** [comment]
that might have to be something to look to gpm and terminal mouse support for.

**Comment by Mirppc** [comment]
I mentioned SDL, why not post a link... so here you go.

https://wiki.libsdl.org/SDL_Event

**Comment by dimitrik-fr** [comment]
Thank you for the info and links !! 
will check it.. 

Rgds,
-Dimitri

**Comment by cosmos72** [comment]
It would be useful, I agree :)

It's quite feasible too: one needs to add support for buttons 4 and 5 in twin mouse events, then update drivers for gpm, xterm mouse, X11 and twin (inception driver) to report such events.

At the moment I don't have much available time to implement it  though...

**Comment by magiblot** [comment]
I think GPM actually supports mouse wheel scrolling (trackpad is another story however).
See the commit linked here: https://github.com/gphalkes/tilde/issues/32

**Comment by cosmos72** [comment]
Yes, thanks :)

let me explain better: if I remember correctly, gpm reports mouse wheel scrolling as clicks of buttons "4" and "5". Twin currently ignores such events, and its various layers should be updated for these additional buttons. Not hard to implement, but needs updating several "hw" drivers: gpm, xterm, X11, twin.
I don't have much time to work on this at the moment, anyway a patch would be welcome :)

**Comment by magiblot** [comment]
Mhm, that's a lot of work. I understand you.
Another desirable functionality would be to have the mouse working for applications ran in a twin terminal.
The only application which does that I have used is `elinks` (because it doesn't need gpm for mouse support, I think). All other gpm applications won't detect mouse events inside twin.
But this is not related to the OP and it's an even more difficult issue. I wanted to mention it though.

**Comment by cosmos72** [comment]
There is a quick-n-dirty hack to convince many applications running in a twin terminal that mouse is supported:  
export TERM=xterm

**Comment by magiblot** [comment]
Oh, wow, that is very interesting. However, some characters don't seem to display correctly for the text editor I'm using (`tilde`). I tried other values and `export TERM=Eterm` finally makes it work for me.

**Comment by cosmos72** [comment]
correction: the various layers already know about mouse buttons 4 and 5 (the scroll wheel) and at least the X11/gfx drivers already generate the correct events.

Then it's just a matter of generating the same events from gpm driver,
and configuring them into $HOME/.twinrc or /usr/local/lib/twin/system.twinrc

**Comment by cosmos72** [comment]
working on it :)

**Comment by cosmos72** [comment]
implemented both window scrolling using mouse wheel, and gpm support for mouse wheel.
See commit a3e13813f376b982f9ecf2592d7ff02edf7d93ee

**Comment by magiblot** [comment]
Awesome. Works great :)

**Comment by cosmos72** [comment]
Good. closing this issue
