### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cosmos72/twin#33]
I would like to point out that identifiers like “[`_TWIN_H`](https://github.com/cosmos72/twin/blob/3e4b3883c342c22923e4995391db6fa98a8cb22e/include/twin.h#L13 "Update candidate")” and “[`_TW_PLUS_PLUS_H`](https://github.com/cosmos72/twin/blob/d074c26d1b65a9f10c6fe78f32134da2f8349f58/include/Tw/Tw%2B%2B.h#L30 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by cosmos72** [comment]
Thanks for spotting this :)
I will rename the #defines starting or ending with `_`

**Comment by cosmos72** [comment]
fixed in [branch c++](https://github.com/cosmos72/twin/tree/c++) commit 57621f2ef92f85c81899a5f4c307460aa6b5558d

**Comment by elfring** [comment]
Thanks for your adjustment of affected include guards.
