### ISSUE TITLE
Contact info invalid

### ISSUE THREAD

**Issue by vanrein** [cosmos72/twin#45]
The repository mentions contact information that seems outdated:

  * Web for http://linuz.sns.it/~max/twin/ reports `Not Found`
  * MX for max@linuz.sns.it reports `454 4.7.1 <max@linuz.sns.it>: Relay access denied`

**Comment by cosmos72** [comment]
Updated in commit c8d9af7793e75ec6398b539ff9fdda160230f4fa, thanks
