### ISSUE TITLE
ALIGN in shm.c redefined on FreeBSD

### ISSUE THREAD

**Issue by frakswe** [cosmos72/twin#56]
shm.c:50:9: warning: 'ALIGN' macro redefined [-Wmacro-redefined]
#define ALIGN 15
        ^
/usr/include/machine/param.h:81:9: note: previous definition is here
#define ALIGN(p)                _ALIGN(p)

**Comment by cosmos72** [comment]
thanks, I will fix this ASAP too

**Comment by cosmos72** [comment]
fixed in [branch c++](https://github.com/cosmos72/twin/tree/c++) commit 57621f2ef92f85c81899a5f4c307460aa6b5558d
