### ISSUE TITLE
twin_real not generated

### ISSUE THREAD

**Issue by ruralchimay** [cosmos72/twin#58]
Hi Boys and Girls,

As a heavy twin user for years, I was eager to test this new version.
Great ! Compiles straight, but complains that "twin_real not found" at launch.
This executable is actually not in the server directory.
Typo in makefile ?

**Comment by cosmos72** [comment]
Yes, there must be a typo somewhere.

The main executable was renamed from twin_real to twin_server some time ago

**Comment by ruralchimay** [comment]
Hi Massimiliano,

Twin_real doesn't exist anymore. Just launch twin_server.
Great changes have occured : compiles straight, dynamic menu and supports utf-8.
I'm glad to see the new twin in action : twin is the ultimate linux desktop.
Feather light, ligthning fast and fully customizable.
You're the man Massimiliano !
Keep going mate, you're beautiful
