### ISSUE TITLE
Issue with Tutf, TT and Tw

### ISSUE THREAD

**Issue by Mirppc** [cosmos72/twin#6]
I was trying to compile twin for use on the 9 dollar computer called CHIP.  In doing so i was getting some errors during the make section.

Here is attempt one using ./config

"~/twin$ make
make -C include
make[1]: Entering directory '/home/chip/twin/include'
make autogen -C Tutf
make[2]: Entering directory '/home/chip/twin/include/Tutf'
make[2]: Nothing to be done for 'autogen'.
make[2]: Leaving directory '/home/chip/twin/include/Tutf'
make autogen -C Tw
make[2]: Entering directory '/home/chip/twin/include/Tw'
make[2]: Nothing to be done for 'autogen'.
make[2]: Leaving directory '/home/chip/twin/include/Tw'
make autogen -C TT
make[2]: Entering directory '/home/chip/twin/include/TT'
m4 -I../../include m4/all.m4h > all_m4.h
/bin/sh: m4: command not found
../../makerules.in:668: recipe for target 'all_m4.h' failed
make[2]: *** [all_m4.h] Error 127
make[2]: Leaving directory '/home/chip/twin/include/TT'
../makerules.in:1047: recipe for target 'autogen-dir-TT' failed
make[1]: *** [autogen-dir-TT] Error 2
make[1]: Leaving directory '/home/chip/twin/include'
makerules.in:1007: recipe for target 'build-dir-include' failed
make: *** [build-dir-include] Error 2
"

Here is the second attempt using make config.
~/twin$ make config
Starting configure for twin 0.6.2_1 ...

/bin/bash scripts/Configure.tty "" ""
#
# Twin configuration utility
#
# Using configuration generated by 'configure' saved in conf.auto
#
# General setup
#
Enable shared libraries [Y/n] ? y
Enable shared modules [Y/n] ? y
Enable Unicode support (libTutf) [Y/n] ? y
Use custom mmap() based malloc/free [Y/n] ? y
Use C type 'long long' if supported (not recommended) [y/N] ? y
Use hand-optimized assembler code if available [y/N] ? y
#
# Socket support
#
Support remote socket connections (libTw) [y/M/n] ? y
 -> Sockets: support gzip compression [y/N] ? y
 -> Sockets: thread-safe libs (requires libpthread) [Y/n] ? y
 -> Sockets: support non-native architectures [Y/n] ? y
#
# Toolkit library support
#
Support Text Toolkit library (libTT) [y/N] ? y
 -> HW support: twin, native [y/M/n] ? y
 -> HW support: twin + server side libTT [y/M/n] ? y
 -> HW support: libTT on twin server side [y/M/n] ? y
 -> HW support: gtk [y/m/N] ? n
 -> HW support: X11 [y/m/N] ? y
 -> HW support: write to xml files [y/M/n] ? y
#
# Window Manager
#
Window Manager: absolutely needed! [y/M/n] ? m
WM: support ~/.twinrc configuration parser [y/M/n] ? y
 -> WM: RC: use mmapped shared file for parser [Y/n] ? y
 -> WM: RC: shrink memory when parser finished [Y/n] ? y
#
# Terminal emulator
#
Builtin Terminal emulator [y/M/n] ? y
 -> Terminal: use Unix98 /dev/pts/* pseudo-ttys [Y/n] ? y
#
# Messages logging
#
Store server messages into Messages window [Y/n] ? y
#
# Display hardware support
#
HW support: text terminals (Linux console...) [y/M/n] ? y
 -> tty support: Linux console (gpm mouse, /dev/vcsa) [Y/n] ? y
 -> tty support: use raw keyboard on Linux console [Y/n] ? y
 -> tty support: twin own terminal [Y/n] ? y
 -> tty support: termcap/ncurses terminal database [Y/n] ? y
HW support: X11 enhanced driver (gfx), uses libXpm [y/m/N] ? y
HW support: X11 [y/m/N] ? y
HW support: twin, native [y/M/n] ? y
HW support: twdisplay client as display [y/M/n] ? y
HW support: libggi [y/m/N] ? n
#
# Server extensions
#
Server extensions [Y/n] ? y
Server extension: Text Toolkit library (libTT) [y/m/N] ? y
#
# Runtime options
#
# Warning: settings in ~/.twinrc or in system.twinrc
# will always override the following options!
Runtime option: enable shadows [Y/n] ? y
Runtime option: enable blink/high background [y/N] ? y
Runtime option: force always visible cursor [y/N] ? y
Runtime option: autohide menu [y/N] ? y
Runtime option: enable menu information line [Y/n] ? y
Runtime option: arrows can open/close submenus [y/N] ? y
Runtime option: enable screen scrolling [Y/n] ? y

~/twin$ make
building  include/Tw/Twautoconf.h
/bin/bash scripts/Configure.tty "" "" < /dev/null > /dev/null || \
/bin/sh scripts/Configure.fallback "" "" < /dev/null > /dev/null
make -C include
make[1]: Entering directory '/home/chip/twin/include'
make autogen -C Tutf
make[2]: Entering directory '/home/chip/twin/include/Tutf'
make[2]: Nothing to be done for 'autogen'.
make[2]: Leaving directory '/home/chip/twin/include/Tutf'
make autogen -C Tw
make[2]: Entering directory '/home/chip/twin/include/Tw'
make[2]: Nothing to be done for 'autogen'.
make[2]: Leaving directory '/home/chip/twin/include/Tw'
make autogen -C TT
make[2]: Entering directory '/home/chip/twin/include/TT'
building include/TT/ttobj.h
/bin/sh: line 2: m4: command not found
building include/TT/ttclass.h
/bin/sh: line 2: m4: command not found
building include/TT/ttobject.h
/bin/sh: line 2: m4: command not found
building include/TT/ttvector.h
/bin/sh: line 2: m4: command not found
building include/TT/ttfield.h
/bin/sh: line 2: m4: command not found
building include/TT/ttmethod.h
/bin/sh: line 2: m4: command not found
building include/TT/ttevent.h
/bin/sh: line 2: m4: command not found
building include/TT/tteventbig.h
/bin/sh: line 2: m4: command not found
building include/TT/ttbitmask.h
/bin/sh: line 2: m4: command not found
building include/TT/tteventmask.h
/bin/sh: line 2: m4: command not found
building include/TT/ttcallback.h
/bin/sh: line 2: m4: command not found
building include/TT/ttlistener.h
/bin/sh: line 2: m4: command not found
building include/TT/tttimer.h
/bin/sh: line 2: m4: command not found
building include/TT/ttcomponent.h
/bin/sh: line 2: m4: command not found
building include/TT/ttdata.h
/bin/sh: line 2: m4: command not found
building include/TT/ttvisible.h
/bin/sh: line 2: m4: command not found
building include/TT/ttlayout.h
/bin/sh: line 2: m4: command not found
building include/TT/ttboxlayout.h
/bin/sh: line 2: m4: command not found
building include/TT/ttborderlayout.h
/bin/sh: line 2: m4: command not found
building include/TT/ttnative.h
/bin/sh: line 2: m4: command not found
building include/TT/ttwidget.h
/bin/sh: line 2: m4: command not found
building include/TT/ttlabel.h
/bin/sh: line 2: m4: command not found
building include/TT/tttooltip.h
/bin/sh: line 2: m4: command not found
building include/TT/ttbuttongroup.h
/bin/sh: line 2: m4: command not found
building include/TT/ttanybutton.h
/bin/sh: line 2: m4: command not found
building include/TT/ttbutton.h
/bin/sh: line 2: m4: command not found
building include/TT/ttcheckbutton.h
/bin/sh: line 2: m4: command not found
building include/TT/ttradiobutton.h
/bin/sh: line 2: m4: command not found
building include/TT/ttanyscroll.h
/bin/sh: line 2: m4: command not found
building include/TT/ttscrollbar.h
/bin/sh: line 2: m4: command not found
building include/TT/ttslider.h
/bin/sh: line 2: m4: command not found
building include/TT/ttprogressbar.h
/bin/sh: line 2: m4: command not found
building include/TT/ttscrollpane.h
/bin/sh: line 2: m4: command not found
building include/TT/ttwindow.h
/bin/sh: line 2: m4: command not found
building include/TT/ttframe.h
/bin/sh: line 2: m4: command not found
building include/TT/ttscroller.h
/bin/sh: line 2: m4: command not found
building include/TT/ttmenuitem.h
/bin/sh: line 2: m4: command not found
building include/TT/ttcheckmenuitem.h
/bin/sh: line 2: m4: command not found
building include/TT/ttradiomenuitem.h
/bin/sh: line 2: m4: command not found
building include/TT/ttmenu.h
/bin/sh: line 2: m4: command not found
building include/TT/ttmenubar.h
/bin/sh: line 2: m4: command not found
building include/TT/ttanytext.h
/bin/sh: line 2: m4: command not found
building include/TT/tttextfield.h
/bin/sh: line 2: m4: command not found
building include/TT/tttextarea.h
/bin/sh: line 2: m4: command not found
building include/TT/tttheme.h
/bin/sh: line 2: m4: command not found
building include/TT/ttapplication.h
/bin/sh: line 2: m4: command not found
m4 -I../../include m4/list.m4h > list_m4.h
/bin/sh: m4: command not found
../../makerules.in:668: recipe for target 'list_m4.h' failed
make[2]: *** [list_m4.h] Error 127
make[2]: Leaving directory '/home/chip/twin/include/TT'
../makerules.in:1047: recipe for target 'autogen-dir-TT' failed
make[1]: *** [autogen-dir-TT] Error 2
make[1]: Leaving directory '/home/chip/twin/include'
makerules.in:1007: recipe for target 'build-dir-include' failed
make: *** [build-dir-include] Error 2

The system is Debian on an Allwinner R8 1ghz arm processor with 512mb ram and 4gb flash.

**Comment by cosmos72** [comment]
you need to install m4
