### ISSUE TITLE
How does Twin perform so well on the linux console?

### ISSUE THREAD

**Issue by magiblot** [cosmos72/twin#61]
Hi cosmos72,

I am testing the performance of [my port of Turbo Vision](https://github.com/magiblot/tvision) on the linux console.

Some optimizations are already in place to reduce the amount of data sent to the terminal:
* Only the cells modified since the last flush are written to stdout.
* SGR attributes get combined into a single sequence (e.g. `\x1B[34;47;22m` instead of `\x1B[34m` `\x1B[47m` `\x1B[22m`).
* Flush frequency limited to 60 FPS.

Yet when a lot of screen cells change between flushes, the display becomes sluggish. For example, when the screen dimensions are large, dragging aggresively a window filled with multibyte characters causes this effect.

I profiled my application under intense screen activity and it spends more time in system than in userspace: 
```py
0.79user 4.03system 0:15.91elapsed 30%CPU (0avgtext+0avgdata 11988maxresident)k
0inputs+0outputs (0major+1988minor)pagefaults 0swaps
```
In accordance, `perf report` says that the most CPU consuming functions are in the kernel:
```py
  21,32%  tvedit   [kernel.kallsyms]    [k] cfb_imageblit
   9,14%  tvedit   [kernel.kallsyms]    [k] do_con_write
   8,59%  tvedit   [kernel.kallsyms]    [k] _raw_spin_lock_irqsave
   5,69%  tvedit   tvedit               [.] BufferedDisplay::screenWrite
   3,34%  tvedit   [kernel.kallsyms]    [k] bit_putcs
   2,63%  tvedit   [kernel.kallsyms]    [k] psi_group_change
   2,40%  tvedit   [kernel.kallsyms]    [k] n_tty_write
   2,12%  tvedit   [kernel.kallsyms]    [k] conv_uni_to_pc
   1,91%  tvedit   [kernel.kallsyms]    [k] native_sched_clock
   1,73%  tvedit   [kernel.kallsyms]    [k] atomic_notifier_call_chain
   1,66%  tvedit   [kernel.kallsyms]    [k] native_write_msr
   1,65%  tvedit   tvedit               [.] FlushScreenAlgorithm::run
   1,51%  tvedit   tvedit               [.] AnsiDisplayBase::writeAttributes
   1,46%  tvedit   [kernel.kallsyms]    [k] fbcon_putcs
```
Yet, Twin is not affected by this. Even if I run my application within twin and then drag the terminal window around, there is no slowdown whatsoever.

GNU Time gives a very similar result for Twin, except for less user overhead, memory usage and page faults:
```py
0.45user 4.49system 0:17.37elapsed 28%CPU (0avgtext+0avgdata 5256maxresident)k
0inputs+0outputs (0major+1175minor)pagefaults 0swaps
```

I checked that page faults are more or less constant and do not increase proportionally to the amount of data sent to the terminal. So that is not the cause of the issue.

`perf report` also gives a similar diagnosis:
```py
  19,83%  twin_server  [kernel.kallsyms]    [k] cfb_imageblit
   5,15%  twin_server  [kernel.kallsyms]    [k] _raw_spin_lock_irqsave
   2,21%  twin_server  [kernel.kallsyms]    [k] do_con_write
   1,92%  twin_server  [kernel.kallsyms]    [k] bit_putcs
   1,62%  twin_server  [kernel.kallsyms]    [k] psi_group_change
   1,36%  tvedit       tvedit               [.] countLines
   1,19%  twin_server  [kernel.kallsyms]    [k] fbcon_putcs
   1,17%  twin_server  [kernel.kallsyms]    [k] __schedule
   1,08%  twin_server  [kernel.kallsyms]    [k] _raw_spin_lock
   1,01%  twin_server  [kernel.kallsyms]    [k] native_write_msr
   0,99%  twin_server  [kernel.kallsyms]    [k] native_sched_clock
   0,94%  twin_server  [kernel.kallsyms]    [k] fbcon_redraw.constprop.0
```

Even most interesting is that an informal benchmark shows that both of them send about the same amount of data to the terminal when quickly dragging a window for ten seconds:
```py
-rw-r--r--   1 magiblot users 38635996 ago 22 19:03  tvdump.txt # tvision: ~36.85 MiB
-rw-r--r--   1 magiblot users 37962337 ago 22 19:05  twdump.txt # twin: ~36.2 MiB
```

I noticed that Twin sometimes uses `ioctl` to interact with the terminal. Instead I let Ncurses set up the terminal and then write directly to stdout.

Another difference is that Twin splits writes to the screen in blocks of 4096 bytes and I write all of the data in a single call to `write`. But I tried the other way around and nothing changed. This can be seen in the `strace` logs [tvtrace.txt](https://github.com/cosmos72/twin/files/5112761/tvtrace.txt) and [twtrace.txt](https://github.com/cosmos72/twin/files/5112762/twtrace.txt).

So, the obvious question is: how can Twin perform this good? Does it configure the terminal in some special way with `ioctl`?

Thank you very much.

**Comment by cosmos72** [comment]
It's very old code, I don't remember every detail.

The first thing coming to my mind is that twin uses non-blocking reads and writes to tty and internally buffers the updates that would block. This, and adding to `select()` writefd_set the fds which would block, is expected to keep twin responsive to user input, avoiding delays and thus sluggishness.

The second is that twin uses `write()` instead of `fwrite()/fprintf()` - although it shouldn't make a big difference .

After the initial setup, the `ioctl()` calls are mostly `ioctl(FIONREAD)` - they return the number of bytes immediately available for reading **without blocking**. If I remember correctly,  it does not use `ioctl(FIONSPACE)`

**Comment by magiblot** [comment]
Hi cosmos, thanks for your answer!

I am not using `ioctl(FIONREAD)` since I do not read input directly. `ncurses` and `gpm` take care of it, and I use `poll` (similar to `select`) to avoid blocking reads.

What I don't check for are blocking writes. Can you explain with a bit more detail how you do it? How do you calculate the amount of data that can be written without blocking? Do you write to the terminal in a separate thread?

From what I can see in the `strace` log I shared above (twtrace.txt), the only syscalls performed on `stdout` are `fstat`, `ioctl(TCGETS)` at the beginning and `write` during program execution.

Thank you.

**Comment by cosmos72** [comment]
Update: I checked the sources, and they use regular, blocking writes with `fputs()/putc()` to stdout - they do **not** use non-blocking writes.
Thus I do not have an obvious explanation for the different behavior.

Maybe you can try `strace -T` or `strace -tt` to identify the source of the delays you are observing with your program.

**Comment by magiblot** [comment]
I'm certainly clueless. I do not see any significant difference in system call delays in the `strace` logs. I also tried making writes to screen asyncronous and the improvement was minimal if not null.

**Comment by magiblot** [comment]
FINALLY, I FOUND IT! :tada:

There is nothing special in the way text is written to the terminal. I was doing all my tests by dragging the mouse; slugginess is the result of receiving GPM mouse events faster than they can be processed due to latency.

I had the feeling Twin was doing some sort of variable refresh rate, but it doesn't. It is simply processing [several mouse events at once](https://github.com/cosmos72/twin/blob/e6c60100f5ec3b4f5e6ebc380c3e9511ae3d0db3/server/hw/hw_tty_linux/mouse_gpm.h#L121) (or discarding them, I haven't gotten into the details).

The Turbo Vision event loop currently flushes the screen once for every attempt at reading an event from whatever source. So this is what needs to be fixed.

I feel a bit frustrated by the fact that I had already realized this in the past. I was impressed by the responsiveness of the Win32 Console version of Turbo Vision compared to my usual Linux terminal emulator and it turned out that Windows' console was discarding mouse events.

**Comment by magiblot** [comment]
Fixed by https://github.com/magiblot/tvision/commit/8d75437258d40c7a8fabb0a78fb11d3e65472feb.

Thanks!

**Comment by cosmos72** [comment]
Good catch! I completely forgot about that part.

Also: twin only updates its in-memory representation of the console when processing each event,
and updates the actual console only after all received events have been processed.

**Comment by magiblot** [comment]
> Also: twin only updates its in-memory representation of the console when processing each event,
> and updates the actual console only after all received events have been processed.

Yes, this is what the patch above fixes. Before that, at most only one event was being processed at a time.

> An alternative solution that could work even better is to merge mouse events, which is very similar to discarding intermediate ones.

There are some drawbacks to this. Firstly, it would have to be implemented separately for text and mouse events so it would be a quirky solution. Secondly, those discarded events could be meaningful to the user application, e.g. if it is a textmode clone of MS Paint (which I doubt anybody would want to make, but is a valid theoretical example).
