### ISSUE TITLE
Opening twin on Ubuntu throws lots of missing library errors

### ISSUE THREAD

**Issue by linuxkettle** [cosmos72/twin#63]
I have used twin a lot with Linux Mint, but I recently moved to Ubuntu MATE and can't run it. I followed the install instructions in README.git, and ran sudo ldconfig afterwards, but it still throws errors about missing libraries:
```
twin: unable to load display driver module `hw_xft' :
      /usr/local/lib/twin/libhw_xft-0.8.1.so: cannot open shared object file: No such file or directory
twin: unable to load display driver module `hw_gfx' :
      /usr/local/lib/twin/libhw_gfx-0.8.1.so: cannot open shared object file: No such file or directory
twin: unable to load display driver module `hw_X11' :
      /usr/local/lib/twin/libhw_X11-0.8.1.so: cannot open shared object file: No such file or directory
twin: starting display driver module `hw_twin'...
      TW_InitHW() failed: TWDISPLAY is not set
twin: ...module `hw_twin' failed to start.
twin: starting display driver module `hw_tty'...
      linux_InitVideo() failed: terminal `xterm-256color' is not `linux'.
twin: ...module `hw_tty' failed to start.
twin: unable to load display driver module `hw_ggi' :
      /usr/local/lib/twin/libhw_ggi-0.8.1.so: cannot open shared object file: No such file or directory
twin: all display drivers failed for `'

twin:  ALL  DISPLAY  DRIVERS  FAILED.  QUITTING.
```
For some reason these libraries are all missing, but there are plenty of other libraries in /usr/local/lib/twin.
If it helps, I'm running Ubuntu MATE 20.04 with Linux kernel 5.8-26 on AMD Kabini A6 (uname -a shows `Linux LAPTOP 5.8.0-26-generic #27-Ubuntu SMP Wed Oct 21 22:29:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by cosmos72** [comment]
Hi, @Kettle3D 
these are warnings, not errors: they say that three alternative libraries (libhw_xft-0.8.1.so libhw_gfx-0.8.1.so and libhw_X11-0.8.1.so) to directly use X11 were not found.

If you want to **only** use twin inside a terminal (i.e. Linux console or some terminal emulator), your setup is ok and you don't need to do anything.

If instead you want twin to directly create a window in your graphical session, you need to install the following libraries, then reconfigure, recompile and reinstall twin:
- libx11-dev
- libxpm-dev
- libxft-dev

**Comment by Mirppc** [comment]
Thanks for giving me a poke to create something. i think i will do a tutorial video on compiling TWIN on a Ubuntu/debian machine!  I did this successfuly on Raspbian and Ubuntu on my Odroid XU4.  So i will do it on PopOS.

**Comment by cosmos72** [comment]
Hello @Mirppc 
thanks! I understand the popularity of videos.
If you are also interested in improving the various README, you would be very welcome :)

**Comment by Kettle3D** [comment]
Thank you @cosmos72, I got it working now. It turned out that the issue I
had was I was launching it with --hw=tty,TERM=xterm-256color instead of
...,TERM=linux.
