### ISSUE TITLE
Long running headless TWIN hangs [on 32-bit system]

### ISSUE THREAD

**Issue by jafcobend** [cosmos72/twin#76]
@cosmos72 I'm moving this from issue #75 since, upon further reflection, it seems a separate issue. I've copied most of this from my report on that issue:

On ARM32 long running TWIN processes seem to hang. How I noticed this was my LEDs stopped blinking!

Let me explain: as mentioned in the configuration discussion I started using TWIN to host long running processes and capture their screen output. The vast majority of the time TWIN is running _headless_. One of those processes checks various /proc files for system status and updates a bank of LEDs via a homemade device on an I2C bus. This is run on a Raspberry Pi 2B. It ran for a day or so and then the LEDs stopped blinking. When I tried to `twattach` the session it claimed there wasn't a TWIN server at that address (`--twin@:0`). `ps` confirmed the processes (TWIN, LEDs, ...) were still there. I had to kill the TWIN server process and restart it.

NOTE: I've been running this process on this device for over a year. Its been running in an xterm hosted by VNC. I was hoping to dump the bloat. :-D

I need to do more testing on this hang issue. It will be a few days to try things. And I'll have to fire up long running TWIN servers on other devices. This issue... needs time to "run long". :-D And hopefully I can come up with things for them to do and remember to check on them. Hmm... I can actually run the exact same programs on all my device types. I just have to sub-out the I2C I/O. I'll do that for the most accurate test.

The output from the programs that I was hosting in the TWIN session is relatively minor. One of the processes basically just marks time, waiting for something to do, spitting out a 30ish char line once a minute or so. It doesn't normally have much to do and this run it did nothing else. The other program  that runs the LEDs is more active spitting out cursor move commands and updating about a dozen chars on the _screen_ every 1/10th second. I'm sure it all accumulates to a significant volume.

I figure I'll have to `gdb` it next time to see if there is something I can make anything out of. Since I'm not familiar with the server architecture that ought to be fun! And I'll have to recompile with debug info. I'll narrow down which architectures have troubles first!

**Comment by Mirppc** [comment]
This is odd.  This must be a regression as i have had TWIN running on my Odroid XU4(Ubuntu), Odroid U2(ARCH), Raspberry pi 1/2/3 (Raspbian), Dell Inspiron 8600 (pentium m and Opensuse Tumbleweed) for long period of times.  I will recompile and test.  I had twin running for over 167 days with no issues on the odroid xu4.

**Comment by jafcobend** [comment]
Sweet! What version of TWIN are you running? I'm running the latest from branch `master` (0.9.0++).

When I setup my tests this morning I found the hung TWIN had survived the `kill` and was still happily dead. And then I was amused that the next TWIN I started took over its socket. ;-) So I `kill -9`d it. So I have a fresh test running to see what happens.

**Comment by cosmos72** [comment]
I had a similar problem, i.e. twin server not responding, and surviving even a `kill`, while analyzing issue #75 on 32-bit arm.
After I fixed that issue, this one disappeared too - at least for me.

Let's both continue keeping an eye on it.

**Comment by jafcobend** [comment]
Yes, I suspect the incorrect buffer sizes could lead to this sort of behavior. :-D Although its been running great for the last four days. I'm going to shut it down and restart it on all devices with the new code. _Now for a "TWIN" to bind them all..._

**Comment by jafcobend** [comment]
@cosmos72 I think you fixed this when fixing the other issue. I've had several long lived sessions. The only reason their life was cut short was due to installing upgraded TWIN. :-) Over three days on the last set of runs. One lets me know if it goes down by its light display failing. But I also routinely ping them through one of the services I'm _hosting_ in TWIN. Things have been rock solid since the fix for issue #75.

A couple other interesting notes:

1. I launched TWIN to run a large rsync (few hundred gigs). I left it spilling file names it was transferring (`-hv`). Killed my terminal and logged back in, twattach'd and it had run to completion! Good job!
2. I had originally launched that TWIN session running through `xterm`. The older `xterm` does a splendid job rendering the TWIN display. The newer one, not so much. I'll have to see if that can be fixed. Anyhow I've seen this happen a few times: I launched my `rsync` in a maximized `twterm`. Then launched an editor to concurrently update a backup job script. One little `twterm`, overlapping a large _full screen_ `twterm`. When the output from the `rsync` gets rapid it causes the edit job to become somewhat unresponsive and the cursor to disappear for periods. Hard to work a screen-oriented editor without knowing where the cursor is and not knowing if your keystrokes are getting through. :-) I killed the `xterm`, re-twattach'd from `twin --hw=X,font=vga` + `twterm` running _full screen_ (HD). The cursor behaved and the terminal I/O was responsive! So `twin --hw=X...` + `twterm` is a superior terminal experience to plain ol' `xterm`. :-D

And that also means my backup job survived multiple terminal disconnects and the running programs ran to completion in headless mode.

I'd call this fixed until I see it break again. But it wasn't that hard to break before. Thanks!

**Comment by cosmos72** [comment]
Good!

About your note on running `twin --hw=tty` inside an `xterm`: IIRC it's known that `xterm` is not the fastest terminal around,
and during intense activity the cursor will inevitably jump around - writing to a terminal intrinsically moves the cursor, and there's no way to avoid it. Putting the cursor back to where it's supposed to be shown helps, but only up to a certain point.

One thing you can try to improve the responsiveness is to use `--hw=tty,slow` (you can get the full list of supported options with the recently added option `--hw=tty,help`)

**Comment by jafcobend** [comment]
I can't say I ever thought to speed-test terminals... that's an interesting thought. But kudos to you for making `twterm` faster! You gotta document that `--hw=tty,help` somewhere in the source package! A shame the other drivers don't support it...

**Comment by cosmos72** [comment]
> I can't say I ever thought to speed-test terminals... that's an interesting thought. But kudos to you for making `twterm` faster! 
Thanks :)

> You gotta document that `--hw=tty,help` somewhere in the source package!
I will. That's why I added it in the first place.

> A shame the other drivers don't support it...
Currently fixing that too.

**Comment by jafcobend** [comment]
Thanks!
