### ISSUE TITLE
I made a deb package and put it into an apt repository

### ISSUE THREAD

**Issue by jdev082** [cosmos72/twin#87]
The repository holding the packages: https://github.com/jdev082/debiverse/
The installation instructions for the repository is here: https://github.com/jdev082/debiverse/#installation

Upon installing the repository, you can install this package by running'

```sudo apt install twin```

This package was built with unmodified source code. If an issue is found with the package please report it to the issues page of my package repository and not here.

**Comment by jdev082** [comment]
Package doesn't work and I can't figure out how to make it work.
```
/usr/bin/twin_server: Symbol `Errstr' has different size in shared object, consider re-linking
twin: unable to load display driver module `hw_xft' :
      (null)
twin: unable to load display driver module `hw_X11' :
      (null)
twin: starting display driver module `hw_twin'...
      TW_InitHW() failed: TWDISPLAY is not set
twin: ...module `hw_twin' failed to start.
twin: starting display driver module `hw_tty'...
      linux_InitVideo() failed: terminal `xterm-256color' is not `linux'.
twin: ...module `hw_tty' failed to start.
twin: all display drivers failed for `'

twin:  ALL  DISPLAY  DRIVERS  FAILED.  QUITTING.
```

**Comment by Mirppc** [comment]
The issue you might find is conflicting packages with some legacy bits that never got removed from the debian repositories.  so please be aware of those if you wish to maintain twin for debian.  you may want to take the mantle of the now orphaned but still offered and built packages.

**Comment by jdev082** [comment]
> The issue you might find is conflicting packages with some legacy bits that never got removed from the debian repositories. so please be aware of those if you wish to maintain twin for debian. you may want to take the mantle of the now orphaned but still offered and built packages.

Where would I find those?

**Comment by Mirppc** [comment]
> > The issue you might find is conflicting packages with some legacy bits that never got removed from the debian repositories. so please be aware of those if you wish to maintain twin for debian. you may want to take the mantle of the now orphaned but still offered and built packages.
> 
> Where would I find those?

They are in the main repos.  I dont recall if it was universe or multiverse or restricted.  It was a bit of an issue when i was compiling on my Odroid and then later on on the Pi.

**Comment by jdev082** [comment]
> > > The issue you might find is conflicting packages with some legacy bits that never got removed from the debian repositories. so please be aware of those if you wish to maintain twin for debian. you may want to take the mantle of the now orphaned but still offered and built packages.
> > 
> > 
> > Where would I find those?
> 
> They are in the main repos. I dont recall if it was universe or multiverse or restricted. It was a bit of an issue when i was compiling on my Odroid and then later on on the Pi.

If I wanted to update the package without waiting for Ubuntu to update it could I just extract the deb, upgrade it, and rebuild?
