### ISSUE TITLE
Problems Compiling Part 2

### ISSUE THREAD

**Issue by Mirppc** [cosmos72/twin#90]
So i was about to go and test something with a freshly pulled and compiled twin but alas i am getting some make errors that are a bit over my head.  This machine has had a working built twin on it (see my youtube videos on the subject).

Attached at the configure logs and the logs from make.

[configure.log](https://github.com/cosmos72/twin/files/12206294/configure.log)

[make.log](https://github.com/cosmos72/twin/files/12206295/make.log)

could this be related to https://github.com/cosmos72/twin/issues/83 ?

**Comment by cosmos72** [comment]
This is unexpected.
Your `make.log` does not contain any error, for some reason it skips compiling the server/ subdirectory.

From what I see, this is on a SUSE Linux box, so `make` should be GNU make.
#83 should be unrelated - it's about some Makefile fragments not working with BSD make.

Can you try running
```
cd /home/mirdellt410/bin/twin && make clean && make && make -d -C server
```
and post the output here?
Thanks

**Comment by Mirppc** [comment]
Thanks for the speedy response.  I did do a Make Clean multiple times to no avail.   Here are the logs.  On another note Sourceforce could never has dreamed of making it this easy to upload logfiles when bug reporting.  I am so glad TWIN moved to github.

All Logs are new btw as of 1:35AM Pacific Time July 29th 2023.
[configure.log](https://github.com/cosmos72/twin/files/12208266/configure.log)

[makeclean.log](https://github.com/cosmos72/twin/files/12208267/makeclean.log)

[make.2.log](https://github.com/cosmos72/twin/files/12208268/make.2.log)

[make.server.log](https://github.com/cosmos72/twin/files/12208269/make.server.log)

**Comment by cosmos72** [comment]
The relevant lines are at the end of your `make.server.log`
```
No implicit rule found for 'hw_display.c'.     Finished prerequisites of target file 'hw_display.c'.                                           Must remake target 'hw_display.c'.          make[1]: Entering directory '/home/mirdellt410/bin/twin/server/hw'                              make[1]: Leaving directory '/home/mirdellt410/bin/twin/server/hw'                               Reaping losing child 0x560ca43ec9e0 PID 7707
```

For some reason, your `make` tries to recreate `server/hw/hw_display.c` which no longer exists - it was renamed `server/hw/hw_display.cpp` long time ago.

I will investigate it.

In the meantime: is it possible that you have some old files in your twin sources directory?
If that's the case, a clean `git clone https:/github.com/cosmos72/twin` in a different directory (followed by `./configure && make -j`) could solve the problem

**Comment by Mirppc** [comment]
huh.

I did a ```git clean -df
git reset --hard origin/master``` and that didnt work out.  i ended up following and trying everything in this stackoverflow thread to no avail. https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files

however when i did a fresh clone into a different directory.  compiled just fine.  Looks like there are some legacy bits that just wont clean up.

**Comment by cosmos72** [comment]
If you still around have the broken working copy,
you can try
```
rm -fr *
git checkout -f
```
**inside** it. That should remove all absolete files.

I'll mark this issue as resolved since a checking out a fresh copy from github fixes the compilation
