### ISSUE TITLE
compiled in w11 wsl 1 ->  Bug ?

### ISSUE THREAD

**Issue by fherking** [cosmos72/twin#92]
Hello, I compiled the source in oracle linux 9.1 running in windows wsl version 1, I can launch the program via params --hw=X11, and all is ok, but windows inside twin doesn't change depth automatically ( I have to use raise/lower to change window position ).

It's a bug, a feature, or an error by my side? Ï am missing any library in compilation?

Ask me for info if needed (libs installed , etc).

Awesome useful piece of code by the way...

**Comment by cosmos72** [comment]
I am somewhat impressed it works at all in WSL.

It's a feature: focusing a window does not raise it automatically: you need to either select "Raise/Lower" from the menu or click on the window button with two vertical arrows.

If you want focusing a window to auto-raise it, you'll need to copy the file `system.twinrc` found in the sources to your `$HOME/.twinrc` and customize it.

**Comment by fherking** [comment]
Ok. 
I thought I was missing some library in compilation , thanks for the info, I made it work...

How it works in wsl (install dependencies) -> compile and  launch twin with :

`twin --hw=X11 `

and use a X11 desktop server like  xming for displaying.

I attach the click for on top solution info in case some one needs this option ->

first : 
`cp  /usr/local/etc/twin/twinrc -> $home/.config/twin/twinrc`

edit the file and add the following line:

`Mouse H1  I  Raise`

**Comment by fherking** [comment]
thanks for all cosmos
