### ISSUE TITLE
How do I change the bloody font? (Times New Roman is just the precursor to Comic Sans, and I hate it)

### ISSUE THREAD

**Issue by TheSystemGuy1337** [cosmos72/twin#93]
Just compiled and installed this on Linux Mint. Problem is the entire thing is in TIMES NEW ROMAN, and it looks ugly with that font. Don't see what I mean? Here: 
![UGLY](https://github.com/cosmos72/twin/assets/61162037/bc854399-a2d8-41e5-81c5-c0e67fa70e32)
Ultimate question: How do I fix this?

**Comment by Mirppc** [comment]
that seems like a terminal issue.  i am using monospace because it is a UTF-8 supported font with extended unicode support (see emoji )  so i would try switching to monospace in your terminal or some other unicode font.
    On Tuesday, August 15, 2023 at 03:58:44 PM PDT, TheSystemGuy1337 ***@***.***> wrote:  
 
 


Just compiled and installed this on Linux Mint. Problem is the entire thing is in TIMES NEW ROMAN, and it looks ugly with that font. Don't see what I mean? Here:

Ultimate question: How do I fix this?

**Comment by TheSystemGuy1337** [comment]
No difference, terminal I launched TWIN from is already on monospaced fonts. Tried installing the VGA fonts as was recommended in the user guide also did nothing. I'm calling it an LM incompatibility, and it's not worth continuing to diagnose for the two people who use TWIN on Linux Mint. Closing.

**Comment by cosmos72** [comment]
@TheSystemGuy1337 judging from your screenshot, you are directly running twin inside X11, not inside some terminal emulator.

In such case, you can choose the font with
```
twin --hw=X11,font=RASTER_FONT_NAME
```
or, if you installed `libxft-dev` (exact package name depends on the Linux distribution) before compiling twin, with
```
twin --hw=xft,font=TRUETYPE_FONT_NAME
```
For best results, you'll need to install some monospace font with good unicode support,
as for example DejaVu Sans Mono.

**Comment by TheSystemGuy1337** [comment]
I would prefer to run TWIN in cool-retro-term instead of XORG X11. How would I force TWIN to accept CRT as a terminal emulator?On Aug 16, 2023, at 2:14 PM, Massimiliano Ghilardi ***@***.***> wrote:﻿
@TheSystemGuy1337 judging from your screenshot, you are directly running twin inside X11, not inside some terminal emulator.
In such case, you can choose the font with
twin --hw=X11,font=RASTER_FONT_NAME

or, if you installed libxft-dev (exact package name depends on the Linux distribution) before compiling twin, with
twin --hw=xft,font=TRUETYPE_FONT_NAME

For best results, you'll need to install some monospace font with good unicode support,
as for example DejaVu Sans Mono.

**Comment by TheSystemGuy1337** [comment]
That fixed my issue. Now I can use Twin in glorious 1024x768 and in monochrome green. Thanks.
![IT WORKS](https://github.com/cosmos72/twin/assets/61162037/51a4f1a1-0c92-46de-b4e5-8f5a38b9a3ea)

**Comment by TheSystemGuy1337** [comment]
One quick question. @cosmos72 
How do I install the optional extras (the calculator as a primary example)

**Comment by cosmos72** [comment]
Good :)

The calculator and other utilities are distributed separately: you'll need to download, compile and install https://github.com/cosmos72/twutils
